apiVersion: batch/v1
kind: Job
metadata:
  name: dsp-clone-job-test-updatedperm-oct10-3-gitops
spec:  
  template:         
    metadata:
      name: dsp-clone-job-test-updatedperm-oct10-3-gitops
    spec:  
      serviceAccountName: test-updatedperm-oct10-3-dsp-job
      containers:
      - name: initialize-dsp
        image: quay.io/redhat-ai-dev/utils:latest
        command:
        - /bin/bash
        - -c
        - |
          NS=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
          oc wait -l statefulset=test-updatedperm-oct10-3-notebook --for=condition=ready pod --timeout=300s
          oc exec  StatefulSet/test-updatedperm-oct10-3-notebook -- git clone https://github.com/test-jdubrick/test-updatedperm-oct10-3
      restartPolicy: Never